title: Justin Malčić
email: justin@malcic.codess
address: |-
  London, UK
description: Graduate software engineer
url: https://malcic.codes
baseurl: ""
twitter_username: jmalcic
github_username:  jmalcic
collections:
  projects:
    output: true
    title: Projects
  posts:
    output: true
    title: Posts
defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "_projects/linguistics"
    values:
      category: linguistics
  - scope:
      path: "_projects/software"
    values:
      category: software
plugins:
  - jemoji
  - jekyll-octicons
